### ISSUE TITLE
Comparing apples to oranges

### ISSUE THREAD

**Issue by lpinca** [alexhultman/faster-than-faster-than-c#1]
From https://github.com/felixge/faster-than-c#introduction

> Before I get started, I would like to appologize for the "Title Bait". **This talk is analyzing the performance of JavaScript vs C-Bindings for MySQL in node.js, but not JavaScript vs. C itself.**

This repo actually compares JavaScript to C++ 😄.
Add a Node.js addon to use the C++ parser from JS land and compare the results of the pure JS implementation with the results of the JS + native addon implementation. This is what the talk was about.

**Comment by lpinca** [comment]
Relevant discussion here https://github.com/felixge/faster-than-c/issues/7.

**Comment by alexhultman** [comment]
Well the whole idea with the "faster-than-c" talk is completely flawed from the beginning. If you look at his "new-parser" you see he's actually reading unsigned integers from memory using a loop like this:

1. read 1-byte
2. Math.pow(256, numberOfBytesRead) it
3. add it to the result
4. repeat until correct byte length

This is made like this, in C:

```c
*(uint16_t *) pointer_to_the_memory
```

Or, more strictly:

```c
uint16_t value;
memcpy(&value, pointer_to_the_memory, sizeof(uint16_t));
```

You can even do similar stuff in JavaScript:

```javascript
var value = buffer.readUInt16LE(offsetInBuffer);
```

This function was added in Node.js 0.5.5, back in 2011, one year prior to his "faster-than-c" talk. As you can see, the actual parser code of "faster-than-c" is a complete and utter joke. It's probably the most ineffective piece of code I have ever seen in my entire life, and the fact that he somehow benchmarked that loop code and concluded it to be "faster-than-c" is just showing how flawed the whole talk is.

The only thing being benchmarked in that talk is, "how fast can I shove this data into a JavaScript object?". When a more sane design would be "don't shove it in, read it zero-copyingly via getters and functions". The problem with this is the data being read is utf-8, while V8 holds strings as utf-16 or latin1, making it impossible to efficiently map the input data with the data being read.

You see, that's kind of the point here. You design the interface from the implementation, not the other way around. If you design the interface from the knowledge of what you need to implement you will get a product with far superior performance. Shoving data into JavaScript objects is never going to scale in any way.

**Comment by alexhultman** [comment]
Call it "Faster than C - shoving data into JavaScript objects" and you have a better title.

**Comment by alexhultman** [comment]
Well actually, call it "Slower than C - shoving data into JavaScript objects" since the node-mariasql module outperformed even his toy parser, so yeah. It's kind of a pointless talk altogether.

**Comment by lpinca** [comment]
I didn't even look at the code and it can be horrible and retarded but this is not the point.
What I'm trying to say is that if you want to bash that claim you have to use a Node.js addon not the C++ code directly.
It is totally possible that even with a native addon perfomance will be better but I doubt it will be 15/20 times better.

**Comment by lpinca** [comment]
Also he said from the beginning that the title was explicitly crafted to get attention so forget about it.

**Comment by alexhultman** [comment]
Sure but then I'm already done, because you can just call the stream function from JS-land and then access the fields with the getStringField getter function. So technically, even if the getStringField will have to make a copy somehow, it's already faster than his "new-parser".

**Comment by alexhultman** [comment]
If the interface allows passing a Node.js buffer and not a String, then I can make it zero-copy.

**Comment by dermidgen** [comment]
@alexhultman I hear what you're saying, and you're absolutely right. It might help your story if you were to publish your toy on npm as a Node.js addon to demonstrate the performance returns even with `getStringField`. @lpinca wouldn't that bring things to be more "apples to apples"? The original piece compared a pure JavaScript module to C++ based Node.js addon.  

I do agree, however, that the original piece from 2012 was attempting to say something that I think @alexhultman is missing. At the time, there was a prevailing belief in the Node.js community that for things like a fast MySQL library, we would only see performance from a C/C++ based Node.js addon. The toy by @felixge was, IMO, simply an attempt to challenge that idea.

Were this published as a Node.js addon, I think this makes an excellent answer to the original toy, and should provide solid insight for libraries already adopting a C/C++ approach. Specifically, https://github.com/mscdex/node-mariasql - see - https://github.com/mscdex/node-mariasql/tree/master/deps/libmariadbclient

**Comment by felixge** [comment]
> I do agree, however, that the original piece from 2012 was attempting to say something that I think @alexhultman is missing. At the time, there was a prevailing belief in the Node.js community that for things like a fast MySQL library, we would only see performance from a C/C++ based Node.js addon. The toy by @felixge was, IMO, simply an attempt to challenge that idea.

This.

**Comment by lpinca** [comment]
> It might help your story if you were to publish your toy on npm as a Node.js addon to demonstrate the performance returns even with getStringField. @lpinca wouldn't that bring things to be more "apples to apples"? The original piece compared a pure JavaScript module to C++ based Node.js addon.

It will definitely be a better comparison see my previous [comment](https://github.com/alexhultman/faster-than-faster-than-c/issues/1#issuecomment-240398710).

**Comment by alexhultman** [comment]
Turns out you can do UTF-8 validation in 10ms, so that brings parsing + validation to about 25ms in total for this particular dump (as compared to ~180-200ms, with uncertainty regarding validation).

The problems with making an addon is:

1. I don't want to.
2. I don't want to rewrite it in Node.js 0.8 when people start claiming the perf increase is because of newer version of Node.js (which is incorrect). I have written addons for Node.js 0.10 and that interface is deprecated and not something I want to relearn.
3. Anyone could see that this interface, and what is being timed in the benchmark is just one single function call "stream". Calling one native function from JS is not going to change perf whatsoever. If you look at the code of Node.js you can see that pretty much every single JS-function is in some way calling into native code, so obviously that is very cheap.
4. I would have to expose a different interface, not a JS object with strings. Then people are going to claim that's the only reason for perf increase (which is true to a very big extent). It can never be a 1-to-1 comparison since I cannot work with the interface of "new-parser", so it will always be some kind of "apples vs oranges".

I'm kind of making a counter-point on my own terms, since I do not agree the benchmark is telling anything else than how fast (or slow) V8 string and object creation is.
